#!/bin/bash

IS_FI=`echo "$LANG" | grep -P "^fi"`
IS_SV=`echo "$LANG" | grep -P "^sv"`

# Defaults to Finnish
DOC_LANG=fi

if [ "${IS_FI}" != "" ]; then
	DOC_LANG=fi
elif [ "${IS_SV}" != "" ]; then
	DOC_LANG=sv
	if [ ! -f /usr/local/share/digabi-koe-ohje/build/index-${DOC_LANG}.html ]; then
		DOC_LANG=fi
	fi
fi

firefox-esr \
-app /usr/lib/firefox-esr/browser/application.ini \
http://localhost/help/build/index.html?lang=${DOC_LANG}&abittiVersion=1
