name: 'Manual Production Release'

on:
  workflow_dispatch:
    inputs:
        tag:
          description: "Tag"
          required: true
          type: string

env:
  IMAGE_NAME: static-cheat

jobs:
  release:
    name: Release private image to public ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/Digabi2PrivateEcrGithubActionsAccessRole
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Pull private image
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:${{ inputs.tag }}
      - name: Configure Public ECR AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/Digabi2PublicEcrGithubActionsAccessRole
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-public-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Tag image
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:${{ inputs.tag }} ${{ steps.login-public-ecr.outputs.registry }}/u3p9b9p9/$IMAGE_NAME-public:${{ inputs.tag }}
      - name: Push image
        run: docker push ${{ steps.login-public-ecr.outputs.registry }}/u3p9b9p9/$IMAGE_NAME-public:${{ inputs.tag }}
      - name: Create Github Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # Pin to commit hash to prevent compromise of third party action
        with:
          tag_name: ${{ inputs.tag }}