name: 'Manual Production Release'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

env:
  DEV_IMAGE_NAME: cheat
  PROD_IMAGE_NAME: cheat-prod
  GITHUB_ACCESS_ROLE: CheatGithubActionsAccessRole

jobs:
  release:
    name: Release private image to public ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/${{ env.GITHUB_ACCESS_ROLE }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Pull private image
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/$DEV_IMAGE_NAME:${{ inputs.tag }}
      - name: Tag image
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/$DEV_IMAGE_NAME:${{ inputs.tag }} ${{ steps.login-ecr.outputs.registry }}/$PROD_IMAGE_NAME:${{ inputs.tag }}
      - name: Push image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$PROD_IMAGE_NAME:${{ inputs.tag }}
      - name: Create Github Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # Pin to commit hash to prevent compromise of third party action
        with:
          tag_name: ${{ inputs.tag }}
