name: Digabi2 Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@538c3eacb0df2e66404e24746ef4f435fdb9cf22
    with:
      app-name: cheat
      aws-access-role: CheatGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
